### ISSUE TITLE
Basic ExampleAgent needed!

### ISSUE THREAD

**Issue by sfstrain** [CognitiveComputingResearchGroup/lidapy-framework#12]
Sean, help! I don't understand--please create an example so that I understand how to use this nice framework you've worked so hard to create!!  Augggggh!!

**Comment by sfstrain** [comment]
Thank you for your changes. Naveen and I pulled it and now old launch cqlida.launch (pushed to repository today) won't work. Fails to find python package lidapy_rosdeps.srv and dies. Also, catkin_make in "root of workspace" lidapy-framework fails to build examples/talker_listener package and roslaunch won't work here either. Help!!!!

**Comment by skugele** [comment]
Two basic examples have been created.  Closing this issue.
