### ISSUE TITLE
Unit Test Cases and Continuous Integration

### ISSUE THREAD

**Issue by skugele** [CognitiveComputingResearchGroup/lidapy-framework#3]
We need to begin working on a set of unit test cases for the Python LIDA framework.  We should also take advantage of GitHub's continuous integration options.

**Outline of steps:**
1. Explore options for Python unit testing
2. Implement the test cases for each module (_We should try to break this up among the team members._)
3. Determine how these test cases can be automatically executed via a GitHub [continuous integration provider](https://github.com/integrations)

**Comment by pulinagrawal** [comment]
Numenta uses [Coveralls](https://github.com/integrations/coveralls) for unit test coverage statistics and [Travis CI](https://github.com/integrations/travis-ci) for build test status.

**Comment by skugele** [comment]
We've integrated Travis CI (go us!), so I am going to close this issue and create a new issue that is targeted specifically at code coverage analysis.
