### ISSUE TITLE
Ambiguity in documentation for lidapy installation 

### ISSUE THREAD

**Issue by sfstrain** [CognitiveComputingResearchGroup/lidapy-framework#40]
"When running the script the first time, you will have to run source ~/.lidapy/setup.bash."

It is unclear whether which of the two scripts should run first.

Also, it would be helpful to add one or two lines explaining precisely what the scripts will do.

**Comment by skugele** [comment]
@pulinagrawal This sfstrain guy is a trouble maker.  We might need to revoke his "issue creation" privileges.

**Comment by pulinagrawal** [comment]
This is wonderful. We got our Kanban Board right here...

**Comment by pulinagrawal** [comment]
@sfstrain I cannot remember enough details to resolve the ambiguity. It seems that setup.bash should be run first. If you are in the process of setting up your machine with lidapy, can you confirm that?

**Comment by skugele** [comment]
I've changed the wording on this section in the README.  Assigning to the originator ( @sfstrain ) to comment on whether this resolved this issue and close.

**Comment by sfstrain** [comment]
The changes address the issue, so I'm closing it.
