### ISSUE TITLE
Default mode of lidapy installation script should be interactive

### ISSUE THREAD

**Issue by sfstrain** [CognitiveComputingResearchGroup/lidapy-framework#42]
Installation of the lidapy framework does not generally proceed without problems. The installation script (currently named /scripts/setup.sh, see previous issue!) should therefore run in interactive mode by default--the additional screen space used will be no more an annoyance than the stdout produced during a ROS installation for instance, and could possibly provide information helpful for debugging a faulty installation.

**Comment by skugele** [comment]
Good suggestion.  I will make this change and update the issue when complete.
