### ISSUE TITLE
Inconsistency between instructions for Ubuntu and non-Ubuntu ROS installations

### ISSUE THREAD

**Issue by sfstrain** [CognitiveComputingResearchGroup/lidapy-framework#43]
Ubuntu: 
$ sudo apt-get install ros-jade-ros-base

Non-Ubuntu: 
$ sudo echo "Installing ROS (the robot OS)" | tee -a /var/tmp/vagrant_prov.log
$ sudo apt-get install -y ros-jade-desktop-full &>>/var/tmp/vagrant_prov.log
$ sudo rosdep init &>>/var/tmp/vagrant_prov.log
$ rosdep -y update &>>/var/tmp/vagrant_prov.log

This is likely to produce dissonant behavior between the two installations.

Perhaps it is better to give the user the link to ROS installation instructions?
http://wiki.ros.org/jade/Installation/Ubuntu 

Will try a new Ubuntu install 
$ sudo apt-get update
$ sudo apt-get install ros-jade-desktop-full
$ sudo rosdep init
$ rosdep update
$ source /opt/ros/jade/setup.bash

**Comment by skugele** [comment]
This issue was addressed in commit de92fe9 by referencing ROS installation instructions in option 1.  Assigning to originator (@sfstrain)  to accept and close.

**Comment by sfstrain** [comment]
The changes addressed the issue, so I'm closing it.
