### ISSUE TITLE
General and In-Code Documentation Needed

### ISSUE THREAD

**Issue by skugele** [CognitiveComputingResearchGroup/lidapy-framework#5]
We need to: 
1. add method / class / module level comments to the code
2. determine if there is a way to externalize the API documentation from the code comments (similar to what we could do with javadoc)
3. document the usage of our configuration files
4. document steps to integration with ROS

When we get further along we will probably want to put together a workshop tutorial paper as well.

**Comment by pulinagrawal** [comment]
For 2, [Epydoc ](http://epydoc.sourceforge.net/manual-epytext.html) seems to be a option that we can use. There were some other options like Doxygen which is not well supported and Sphinx that looks somewhat complicated at first.

**Comment by skugele** [comment]
Doxygen as an option is interesting.  I've used Doxygen for C/C++ documentation in the past.  I didn't realize that there was an attempt to apply it to Python.  

The [Python wiki](https://wiki.python.org/moin/DocumentationTools) has good things to say about it:

> Doxygen < http://www.doxygen.org > can create documentation in various formats (HTML, LaTeX, PDF, ...) and you can include formulas in your documentation (great for technical/mathematical software). Together with Graphviz < http://www.research.att.com/sw/tools/graphviz/ > it can create diagrams of your code (inhertance diagram, call graph, ...). Another benefit is that it handles not only Python, but also several other programming languages like C, C++, Java, etc.

Based on the same page, it looks like Epydoc is no longer under development (no bug fixes), so that has me a little concerned about using it.  (However, it does look like javadoc, which is nice.)

Personally, I would like to play around a little bit with Doxygen to see how well it works with Python.  If you are right, and it isn't well supported, then we can check out the other options.

Thanks for posting! @pulinagrawal

**Comment by skugele** [comment]
Closing this issue as it is non-productive.
